version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.2
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns,sts,ses,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - yantech

  admin:
    build: ./admin
    ports:
      - "5001:5001"
    env_file:
      - ./admin/.env.example
    depends_on:
      - localstack
    networks:
      - yantech

  app:
    build: ./app
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env.example
    depends_on:
      - localstack
    networks:
      - yantech

  worker:
    build: ./worker
    env_file:
      - ./worker/.env.example
    depends_on:
      - localstack
    networks:
      - yantech

volumes:
  localstack_data:

networks:
  yantech:
    driver: bridge