version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,ses,sns,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init/init_localstack.sh:/etc/localstack/init/ready.d/init_localstack.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - yantech

  admin:
    build: ./adminstratorCode
    container_name: admin
    ports:
      - "5001:5001"
    env_file:
      - ./adminstratorCode/.env.example
    depends_on:
      - localstack
    networks:
      - yantech

  app:
    build: ./requestorCode
    container_name: requester
    ports:
      - "5000:5000"
    env_file:
      - ./requestorCode/.env.example
    depends_on:
      - localstack
    networks:
      - yantech

  worker:
    build: ./workerCode
    container_name: worker
    env_file:
      - ./workerCode/.env.example
    depends_on:
      - localstack
    networks:
      - yantech

volumes:
  localstack_data:

networks:
  yantech:
    driver: bridge





    